return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	opts = {
		ensure_installed = {
			"bash",
			"cpp",
			"dockerfile",
			"helm",
			"html",
			"javascript",
			"json",
			"lua",
			"markdown",
			"markdown_inline",
			"python",
			"query",
			"regex",
			"rust",
			"tsx",
			"typescript",
			"vim",
			"yaml",
		},
		highlight = { enable = true },
		incremental_selection = { enable = true },
		indent = { enable = false },
	},
}
